# Numpy Reshape

In [1]:
# Import the required libraries.
import numpy as np

In [2]:
# Create a sample numpy matrix.
sample_numpy = np.array([[1,2,3],[4,5,6],[7,8,9]])
sample_numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# sample_numpy is a numpy.ndarray.
type(sample_numpy)

numpy.ndarray

In [4]:
# Now we want to flat this matrix (Change it from 3*3 matrix to 9-element list).
sample_numpy_reshaped1 = np.reshape(sample_numpy, -1)
sample_numpy_reshaped1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# sample_numpy_reshaped1 is still a numpy.ndarray.
type(sample_numpy_reshaped1)

numpy.ndarray

In [6]:
# This code has the same result ('-1' is equivalent to size of the matrix).
sample_numpy_reshaped2 = np.reshape(sample_numpy, 9)
sample_numpy_reshaped2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# This is another way to flat the matrix (column-wise).
sample_numpy_reshaped3 = np.reshape(sample_numpy, -1, order='F')
sample_numpy_reshaped3

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [8]:
# Reshape the matrix from 3*3 to 9*1.
np.reshape(sample_numpy, (9,-1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [9]:
# Now consider this matrix.
sample_numpy2 = np.zeros((12,2))
sample_numpy2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
# Let's reshape this matrix from 12*2 to 3*8.
sample_numpy2_reshaped1 = np.reshape(sample_numpy2, (3, 8))
sample_numpy2_reshaped1

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
# Consider this new matrix.
sample_numpy3 = np.arange(6).reshape((3, 2))
sample_numpy3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
# We want to reshape it from 3*2 to 2*3.
sample_numpy3_reshaped1 = np.reshape(sample_numpy3, (2,3))
sample_numpy3_reshaped1

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
# This another way for reshaping (column-wise).
sample_numpy3_reshaped2 = np.reshape(sample_numpy3, (2, 3), order='F')
sample_numpy3_reshaped2

array([[0, 4, 3],
       [2, 1, 5]])